"""create consoles table

Revision ID: 5e7a54fc29e0
Revises: 6e205a5fe557
Create Date: 2025-12-24 14:59:08.165119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7a54fc29e0'
down_revision: Union[str, Sequence[str], None] = '6e205a5fe557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consoles_company'), 'consoles', ['company'], unique=False)
    op.create_index(op.f('ix_consoles_id'), 'consoles', ['id'], unique=False)
    op.create_index(op.f('ix_consoles_name'), 'consoles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consoles_name'), table_name='consoles')
    op.drop_index(op.f('ix_consoles_id'), table_name='consoles')
    op.drop_index(op.f('ix_consoles_company'), table_name='consoles')
    op.drop_table('consoles')
    # ### end Alembic commands ###
